config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "patients/menu", to: "patients#option", as: :option
  get "patients/list", to: "patients#list", as: :list
  get "patients/appointments", to: "appointments#index"
  get "appointments/invoice", to: "appointments#invoice", as: :invoice
  get "/" => "home#index"
  get "/doctors/home" => "doctors#home"
  get "/unseen" => "appointments#unseen"
  get "/seen" => "appointments#seen"
  get "/upcoming" => "appointments#upcoming"
  get "/blocked" => "patients#blocked"
  post "/done/:id" => "appointments#done"
  post "/unblock/:id" => "patients#unblock"
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :doctors
  resources :appointments
  resources :patients
  resources :specializations
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/specialization.rb
class Specialization < ApplicationRecord
  has_many :doctors
  has_many :hospitals, through: :doctors
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
    skip_before_action :ensure_user_login
  
    def new
      render "specializations/new"
    end
  
    def create
      specialization = Specialization.new(
        name: params[:name],
      )
      specialization.save
      flash[:notice]="Specialization Created!!"
      redirect_to patients_path
    end
end

app/views/specializations/new.html.erb
<section class="block">
  <p class="NewUsers-title"> Specialization Creation !!</p>
  <div class="parent-div">
    <section class="UsersNew">
      <%= form_with url: specializations_path do |form|%>
        <div class="Form-section">
          <p class="Form-InputLabel">Name: </p>
          <%= form.text_field :name , class: "Form-input",autofocus: "autofocus"%>
        </div>
        <div class="Form-section">
          <%= form.submit "Create" ,class: "Form-submit"%>
        </div>
      <% end %>
    </section>
  </div>
</section>