config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "patients/menu", to: "patients#option", as: :option
  get "patients/list", to: "patients#list", as: :list
  get "patients/appointments", to: "appointments#index"
  get "appointments/invoice", to: "appointments#invoice", as: :invoice
  get "/" => "home#index"
  get "/doctors/home" => "doctors#home"
  get "/unseen" => "appointments#unseen"
  get "/seen" => "appointments#seen"
  get "/upcoming" => "appointments#upcoming"
  get "/blocked" => "patients#blocked"
  post "/done/:id" => "appointments#done"
  post "/unblock/:id" => "patients#unblock"
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :doctors
  resources :appointments
  resources :patients
  resources :specializations
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @current_user = current_user
    if @current_user.role == "patient"
      render "index"
    elsif @current_user.role == "admin"
      render "show"
    end
  end

  def option
    @display = false
    @current_user=current_user
    render "option"
  end

  def list
    render "list"
  end
  
  def blocked
    @blocked = Patient.where(is_blocked: true)
    render "blocked"
  end

  def unblock
    patient = Patient.find(params[:id])
    appointment = patient.appointments.where("status = ? and appointment_time < ?",false,DateTime.now.in_time_zone("Chennai")).first
    appointment.update(status: true)
    patient.update(is_blocked: false)
    flash[:notice] = "Patient Unblocked Successfully!"
    redirect_to patients_path
  end
  
  def update
    name=params[:name]
    email=params[:email]
    password=params[:password]
    user = @current_user.update(name: name,email: email,password: password)
    if user
      flash[:notice] = "Profile edited successfully"
      redirect_to patients_path
    else
      flash[:error] = "Field cannot be empty"
      redirect_to patient_path
    end
  end

  def destroy
    id=params[:id]
    patient = Patient.find(id)
    user=patient.user
    user.destroy
    redirect_to patients_path
  end

  def show
    @current_user = current_user
    render "profile"
  end 
end

app/views/patients/blocked.html.erb
<section class="block">
    <h1 class="welcome-head head">Blocked Patients</h1>
    <table class="Appointments-table">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Unblock</th>
        </tr>
        <% @blocked.each do |t| %>
            <tr>
                <td><%= t.user.id %></td>
                <td><%= t.user.name %></td>
                <td><%= t.user.gender %></td>
                <td><%= t.user.email %></td>
                <td>
                    <%= form_with(url: "/unblock/#{t.id}", method: "post") do |form| %>
                        <%= form.submit "Unblock", class: "buttons" %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</section>

app/views/patients/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>

  <div class="s_search_area well">
    <div class="s_specialization">
      <label for="specialization" >Choose the specialization</label>
      <select name="specialization" id="specialization" class="s_select_specialization" onchange="populate(this.id)">
        <% Specialization.all.each do |specialization| %>
          <option value="<%= specialization.name %>" ><%= specialization.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div id="main_div" class="s_main_div">
    <% Specialization.first.doctors.each do |doctor| %>
      <div class="s_box">
        <h1 class="s_box_name">Dr. <%= doctor.user.name %></h1>
        <div class="s_box_sec">
          <p class="s_box_avail">Available : </p>
          <% if !doctor.mon.empty?() %>
            <p class="s_box_days">Mon,</p>
          <% end %>
          <% if !doctor.tue.empty?() %>
            <p class="s_box_days">Tue ,</p>
          <% end %>
          <% if !doctor.wed.empty?() %>
            <p class="s_box_days">Wed ,</p>
          <% end %>
          <% if !doctor.thu.empty?() %>
            <p class="s_box_days">Thu ,</p>
          <% end %>
          <% if !doctor.fri.empty?() %>
            <p class="s_box_days">Fri ,</p>
          <% end %>
          <% if !doctor.sat.empty?() %>
          <p class="s_box_days">Sat ,</p>
          <% end %>
          <% if !doctor.sun.empty?() %>
            <p class="s_box_days">Sun</p>
          <% end %>
        </div>
        <form action="/appointments/<%= doctor.id %>" method="GET">
          <input type="submit" value="Book Appointment">
        </form>
      </div>

    <% end %>

  <div>
</body>
<script>
  function populate(s1)
  {
    var select1 = document.getElementById(s1);
    var main = document.getElementById("main_div");
    let arr=[];
    var child = main.lastElementChild;
        while (child) {
            main.removeChild(child);
            child = main.lastElementChild;
        }
    <% Specialization.all.each do |specialization| %>
      if(select1.value=="<%= specialization.name %>")
      {
        <% specialization.doctors.each do |doctor| %>
          var div = document.createElement("div");
          div.className = "s_box";
          var div1 = document.createElement("div");
          div1.className = "s_box_sec";
          var h1 = document.createElement("h1");
          h1.innerHTML = "Dr. " + "<%= doctor.user.name %>";
          h1.className = "s_box_name";
          var p = document.createElement("p");
          p.className = "s_box_avail";
          p.innerHTML = "Available :";
          var form = document.createElement("form");
          form.setAttribute("method","get");
          form.setAttribute("action","/appointments/<%= doctor.id %>")
          var s = document.createElement("input");
          s.setAttribute("type", "submit");
          s.setAttribute("value", "Book Appointment");
          var p1 = new Array(7);
          for(var i=0;i<p1.length;i++)
          {
            p1[i]=document.createElement("p");
            p1[i].className = "s_box_days";
          }
          <% if !doctor.mon.empty?() %>
            p1[0].innerHTML = "Mon,";
          <% end %>
          <% if !doctor.tue.empty?() %>
            p1[1].innerHTML = "Tue,";
          <% end %>
          <% if !doctor.wed.empty?() %>
            p1[2].innerHTML = "Wed,";
          <% end %>
          <% if !doctor.thu.empty?() %>
            p1[3].innerHTML = "Thu,";
          <% end %>
          <% if !doctor.fri.empty?() %>
            p1[4].innerHTML = "Fri,";
          <% end %>
          <% if !doctor.sat.empty?() %>
            p1[5].innerHTML = "Sat,";
          <% end %>
          <% if !doctor.sun.empty?() %>
            p1[6].innerHTML = "Sun";
          <% end %>
          div.appendChild(h1);
          div1.appendChild(p);
          for(var i=0;i<p1.length;i++)
            div1.appendChild(p1[i]);
          div.appendChild(div1);
          form.appendChild(s);
          div.appendChild(form);
          main.appendChild(div);
        <% end %>
      }
    <% end %>
  }
</script>
</html>

app/views/patients/list.html.erb
<body class="s_main_body">
  <%= form_with(url: patients_path, method: "get") do %>
        <%= image_submit_tag('cancel.svg',class: "s_cancel") %>
  <% end %>
  <div class="s_option_pane">
    <p><%= link_to "Unseen Appointments", "/unseen", class: "links" %></p>
    <p><%= link_to "Upcoming Appointments", "/upcoming" , class: "links" %></p>
    <p><%= link_to "Seen Appointments", "/seen" , class: "links" %></p>
    <p><%= link_to "Blocked Patients", "/blocked" , class: "links" %></p>
    <p><%= link_to "Sign-out", destroy_session_path , method: "delete",class: "s_option" %></p>
  </div>
</body>

app/views/patients/option.html.erb
<body class="s_main_body">
  <%= form_with(url: patients_path, method: "get") do %>
        <%= image_submit_tag('cancel.svg',class: "s_cancel") %>
  <% end %>
  <div class="s_option_pane">
    <p><%= link_to "Home", patients_path , method: "get",class: "s_option" %></p>
    <p><%= link_to "Profile", "/patients/#{@current_user.id}", method: "get", class: "s_option"%></p>
    <p><%= link_to "History", appointments_path, method: "get",class: "s_option" %></p>
    <p><%= link_to "Sign-out", destroy_session_path , method: "delete",class: "s_option" %></p>
  </div>
</body>

app/views/patients/profile.html.erb
<div class="s_profile">
<h1>User Details</h1>
  <div class="s_logo"><p class="s_logo"><%= @current_user.name[0] %></p></div>
  <section class="s_signup-section">
    <%= form_with url: "/patients/#{@current_user.id}", method: :put do |form| %>
      <div class="s_profile_details">
        <%= form.label :name, "Name  :", class: "s_labels" %>
        <%= form.text_field :name, class: "s_fields" %>
      </div>
      <div class="s_profile_details">
        <%= form.label :email, "Email  :", class: "s_labels" %>
        <%= form.email_field :email, class: "s_fields" %>
      </div>
      <div class="s_profile_details">
        <%= form.label :password, "Password:", class: "s_labels" %>
        <%= form.password_field :password, class: "s_fields" %>
      </div>
      <%= form.submit :Save, class: "s_buttons" %>
    <% end %>
    <hr class="s_new">
    <div class="s_appointment_details">
      <h1>Appointments taken</h1>
      <div class="s_profile_detail1">
        <h3 class="s_label1">Total : </h3>
        <h3 class="s_field1"><%= @current_user.total%></h3>
      </div>
      <div class="s_profile_detail1">
        <h3 class="s_label1">Seen : </h3>
        <h3 class="s_field1"><%= @current_user.seen%></h3>
      </div>
      <div class="s_profile_detail1">
        <h3 class="s_label1">Unseen : </h3>
        <h3 class="s_field1"><%= @current_user.unseen%></h3>
      </div>
    <div>
  </section>
</div>

<script>
    window.onload = function myfunc() {
        var name = document.getElementById("name");
        name.value = "<%= @current_user.name %>";
        name = document.getElementById("email");
        name.value = "<%= @current_user.email %>";
    }
</script>

app/views/patients/show.html.erb
<section class="block">
<p class="NewUsers-title"> Patient Details </p>
<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Blocked status</th>
    <th>Email</th>
  </tr>
  <% Patient.all.each do |pa| %>
      <tr>
        <td><%= pa.user.name %></td>
        <td><%= pa.is_blocked %></td>
        <td><%= pa.user.email %></td>
        <td>
          <%= form_with(url: "/patients/#{pa.id}", method: "delete") do %>
            <%= image_submit_tag('delete.svg',class: "s_delete") %>
          <% end %>
        </td>
      </tr>
  <%end%>
</table>

<p class="NewUsers-title"> Appointments for Today </p>
<table class="table table-bordered">
  <tr>
    <th>Id</th>
    <th>Date</th>
    <th>Time</th>
    <th>Status</th>
    <th>Mark as done</th>
  </tr>
    <% Appointment.all.each do |appointment| %>
      <% if appointment.appointment_time.today? and appointment.status == false %>
        <tr>
          <td><%= appointment.id %></td>
          <td><%= appointment.appointment_time.strftime("%d-%b-%Y")%></td>
          <td> <%= appointment.appointment_time.strftime("%I : %M %p") %></td>
          <td><%= appointment.status ? "Completed" :  "Pending" %></td>
          <td>
            <%= form_with(url: "/done/#{appointment.id}", method: "post") do |form| %>
                <%= form.submit "Mark as done", class: "buttons" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
</table>

<p class="NewUsers-title"> Specialization Details </p>
<% Specialization.all.each do |s| %>
  <div style="display: grid">
      <h3>  Specialization : <%=s.name%> </h3>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Delete</th>
        </tr>
        <% s.doctors.each do |t| %>
          <tr>
              <td><%= t.user.name %></td>
              <td><%= t.user.email %></td>
              <td>
                  <%= form_with(url: "/doctors/#{t.id}", method: "delete") do %>
                    <%= image_submit_tag('delete.svg',class: "s_delete") %>
                  <% end %>
              </td> 
          </tr>
        <%end%>
      </table>
  </div>
<%end%>
<hr>
<h3 class="Home-authenticate" >
  To create Doctor , <%= link_to "click here", new_user_path %>
</h3>

<h3 class="Home-authenticate" >
  To create Specialization , <%= link_to "click here", new_specialization_path %>
</h3>
</section>