config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "patients/menu", to: "patients#option", as: :option
  get "patients/list", to: "patients#list", as: :list
  get "patients/appointments", to: "appointments#index"
  get "appointments/invoice", to: "appointments#invoice", as: :invoice
  get "/" => "home#index"
  get "/doctors/home" => "doctors#home"
  get "/unseen" => "appointments#unseen"
  get "/seen" => "appointments#seen"
  get "/upcoming" => "appointments#upcoming"
  get "/blocked" => "patients#blocked"
  post "/done/:id" => "appointments#done"
  post "/unblock/:id" => "patients#unblock"
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :doctors
  resources :appointments
  resources :patients
  resources :specializations
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
  belongs_to :hospital
  belongs_to :specialization
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  def first_five
    appointments.where(status: false).take(5)
  end

  def unseen
    appointments.where(status: false)
  end

  def seen
    appointments.where(status: true)
  end

  def self.day(t)
    Date.today.next_day(t).strftime("%a %d %b").to_s
  end

  def available?(i,day_name)
    if day_name.include?(i+1)
      true
    else
      false
    end
  end

  
  def booked(day,slot)
    appointments.where(status:  false).each do |appointment|
      diff = ((appointment.appointment_time - DateTime.now)/(24*3600)).floor
      if diff == day && appointment.appointment_time.strftime("%H").to_i - 8 == slot+1
        return true
      end
    end
    false
  end
  

  def find_day(t)
    t = (t + Date.today.cwday - 1).modulo(7)
    case t
    when 0
      mon
    when 1
      tue
    when 2
      wed
    when 3
      thu
    when 4
      fri
    when 5
      sat
    when 6
      sun
    end
  end

  def available(t,i)
    day_name = find_day(t)
    available?(i,day_name)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    render :index
  end

  def edit
    render :edit
  end

  def home
    render :home
  end

  def update
    if params[:td]
      param = params[:td]
      day = param[0].to_i
      slot = param[2..-1].to_i
      doctor = @current_user.doctor
      if doctor.available(day,slot)
        doctor.find_day(day).delete(slot+1)
      else
        doctor.find_day(day).push(slot+1)
      end
      doctor.save!
      redirect_to edit_doctor_path
    else
      name = params[:name]
      email = params[:email]
      password = params[:password]
      gender = params[:gender]
      user = @current_user.update(name: name,email: email, password: password, gender: gender)
      if user
        flash[:notice] = "Updated Successfully!"
        redirect_to "/doctors/home"
      else
        flash[:error] = "Invalid input!"
        redirect_to "/doctors/#{@current_user.doctor.id}/edit"
      end
    end
  end
  def destroy
    id=params[:id]
    doctor = Doctor.find(id)
    doctor.user.destroy
    redirect_to patients_path
  end
end

app/views/doctors/edit.html.erb
<section class="block">
    <h1 class="welcome-head head">Healthcare Manager</h1>
    <div class="Doctor-NavigationButtons">
        <%= link_to "Back", doctors_path, class: "buttons" %>
        <%= link_to "Home", "/doctors/home", class: "buttons" %>
    </div>
    <div class="Schedule">
        <p class="Schedule-head">Edit Schedule</p>
        <table class="Schedule-table">
            <tr>
                <th>Day</th>
                <% 11.times.each do |t| %>
                    <th><%= t+1 %></th>
                <% end %>
            </tr>
            <% 7.times.each do |t| %>
                <tr>
                    <td>
                        <%= Doctor.day(t) %>
                    </td>
                    <% 11.times.each do |i| %>
                        <% if t > 2 %>
                            <%= form_with url: "/doctors/#{@current_user.doctor.id}",id: "#{t},#{i}", method: :put do |form| %>
                                <td class= '<%= @current_user.doctor.available(t,i) ? "available-slot" : "not-available-slot" %> cursor-available' onclick='document.getElementById("<%= "#{t},#{i}" %>").submit()' >
                                    <%= form.hidden_field :td, value: "#{t},#{i}" %>
                                    <%= "#{i+9} : #{i+10}" %>
                                </td>
                            <% end %>
                        <% else %>
                            <td class= '<%= @current_user.doctor.available(t,i) ? "available-slot" : "not-available-slot" %> no-cursor' >
                                <%= "#{i+9} : #{i+10}" %>
                            </td>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
        </table>
    </div>
    <hr>
    <div class="EditProfile">
        <p class="EditProfile-head">Edit Profile</p>
        <section class="signup-section">
            <%= form_with url: "/doctors/#{@current_user.id}", method: :put do |form| %>
                <div class="signup-fields">
                    <%= form.label :name, "Name:", class: "labels" %>
                    <%= form.text_field :name, class: "fields" %>
                </div>
                <div class="signup-fields">
                    <%= form.label :email, "Email:", class: "labels" %>
                    <%= form.email_field :email, class: "fields" %>
                </div>
                <div class="signup-fields">
                    <%= form.label :password, "Password: (Enter old or new password)", class: "labels" %>
                    <%= form.password_field :password, class: "fields" %>
                </div>
                <div class="signup-gender">
                    <p class="gender-head">Gender</p>
                    <div class="radio-button-div">
                        <%= form.radio_button :gender, "male", class: "radio-edit" %>
                        <%= form.label :male, "Male" %>
                        <%= form.radio_button :gender, "female", class: "radio-edit" %>
                        <%= form.label :female, "Female" %>
                    </div>
                </div>
                <%= form.submit :Save, class: "buttons" %>
            <% end %>
        </section>
    </div>
</section>

<script>
    window.onload = function myfun() {
        var name = document.getElementById("name");
        name.value = "<%= @current_user.name %>";
        name = document.getElementById("email");
        name.value = "<%= @current_user.email %>";
        var gender = "<%= @current_user.gender %>";
        name = document.getElementById("gender_"+gender);
        name.checked = true;
    }
</script>

app/views/doctors/home.html.erb
<section class="block">
    <h1 class="welcome-head head">Healthcare Manager</h1>
    <div class="Doctor-NavigationButtons">
        <%= link_to "Back", doctors_path, class: "buttons" %>
        <%= form_with url: "/doctors/#{@current_user.doctor.id}/edit", method: :get do |form| %>
            <%= form.submit "Edit Profile", class: "buttons" %>
        <% end %>
    </div>
    <div class="Profile">
        <p class="Profile-head">Profile</p>
        <p class="profile-labels">Name : <%= @current_user.name %></p>
        <p class="profile-labels">Email : <%= @current_user.email %></p>
        <p class="profile-labels">Gender : <%= @current_user.gender %></p>
        <p class="profile-labels">Hospital : <%= @current_user.doctor.hospital.name %>
        <p class="profile-labels">Specialization : <%= @current_user.doctor.specialization.name %>
        <p class="profile-labels">Total Appointments : <%= @current_user.doctor.appointments.count %>
        <p class="profile-labels">Unseen Appointments : <%= @current_user.doctor.appointments.where(status: false).count %>
    </div>
    <hr>
    <div class="appointments-list">
        <%= render partial: "appointments-section", locals: {section_title: "Unseen Appointments", current_appointments: @current_user.doctor.unseen} %>
        <div>
          <hr>
        </div>
        <%= render partial: "appointments-section", locals: {section_title: "Seen Appointments", current_appointments: @current_user.doctor.seen} %>
    </div>
</section>
<script>
  var i; 
  function openpop(id){
    i = id;
    var popupdiv = document.getElementById(id);
    popupdiv.style.display="block";
  }
  function closepop(){
    var popupdiv = document.getElementById(i);
    popupdiv.style.display="none";
  }
</script>

app/views/doctors/index.html.erb
<section class="block">
    <h1 class="welcome-head head">Healthcare Manager</h1>
    <div class="Doctor-NavigationButtons">
        <%= form_with url: "/signout", method: :delete do |f| %>
            <%= f.submit "Sign out", class: "buttons" %>
        <% end %>
        <%= link_to "Home", "/doctors/home", class: "buttons" %>
    </div>
    <div class="Upcoming-appointments">
        <%= render partial: "appointments-section", locals: {section_title: "Upcoming Appointments", current_appointments: @current_user.doctor.first_five} %>
    </div>
    <div class="Schedule">
        <p class="Schedule-head">Schedule</p>
        <%= form_with url: "/doctors/#{@current_user.doctor.id}/edit", method: :get, class: "Doctor-edit-button" do |form| %>
            <%= form.submit "Edit Profile", class: "buttons" %>
        <% end %>
        <table class="Schedule-table cursor-type">
            <tr>
                <th>Day</th>
                <% 11.times.each do |t| %>
                    <th><%= t+1 %></th>
                <% end %>
            </tr>
            <% 7.times.each do |t| %>
                <tr>
                    <td>
                        <%= Doctor.day(t) %>
                    </td>
                    <% 11.times.each do |i| %>
                        <td class= '<%= @current_user.doctor.available(t,i) ? "available-slot" : "not-available-slot" %>'>
                            <%= "#{i+9} : #{i+10}" %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </table>
    </div>
</section>
<script>
  var i; 
  function openpop(id){
    i = id;
    var popupdiv = document.getElementById(id);
    popupdiv.style.display="block";
  }
  function closepop(){
    var popupdiv = document.getElementById(i);
    popupdiv.style.display="none";
  }
</script>