config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "patients/menu", to: "patients#option", as: :option
  get "patients/list", to: "patients#list", as: :list
  get "patients/appointments", to: "appointments#index"
  get "appointments/invoice", to: "appointments#invoice", as: :invoice
  get "/" => "home#index"
  get "/doctors/home" => "doctors#home"
  get "/unseen" => "appointments#unseen"
  get "/seen" => "appointments#seen"
  get "/upcoming" => "appointments#upcoming"
  get "/blocked" => "patients#blocked"
  post "/done/:id" => "appointments#done"
  post "/unblock/:id" => "patients#unblock"
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :doctors
  resources :appointments
  resources :patients
  resources :specializations
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthcareManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    
    <% if @display != false && @current_user && @current_user.email_confirmed && @current_user.role == "patient" %>
      <div class="s_header">
        <%= form_with(url: option_path, method: "get") do %>
          <%= image_submit_tag('threebar.svg',class: "s_threebar") %>
        <% end %>
        <h1>Sree krishna Hospitals</h1>
      </div>
    <% end %>
    
    <% if @current_user && @current_user.role == "admin" %>
      <div class="s_header">
        <%= form_with(url: list_path, method: "get") do %>
          <%= image_submit_tag('threebar.svg',class: "s_threebar") %>
        <% end %>
        <h1>Sree krishna Hospitals</h1>
      </div>
    <% end %>

    <% if flash[:error] %>
      <p class= "Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
  
    <% if flash[:notice] %>
      <p class= "Flash-notice">
        <%= flash[:notice] %>
      </p>
    <% end %>
    
    <%= yield %>
    
  </body>
</html>